[package]
name = "snaek"
version = "0.1.0"
authors = ["Brett Jurman <i.be.brett@gmail.com>"]
edition = "2019"

[dependencies]
rand = "0.7.0"
cgmath = "0.17.0"


[dependencies.sdl2]
version = "0.32.2"
features = ["gfx"]
